import sqlite3, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
conn = sqlite3.connect(r'g:\project\github\bible\resource\s_.db')
print('=== gfhl (Greek Strong) sample ===')
rows = conn.execute('SELECT gsnum, txt, orig FROM gfhl LIMIT 3').fetchall()
for r in rows:
    print(f'gsnum={r[0]}, txt={str(r[1])[:80]}, orig={str(r[2])[:40]}')
print()
print('=== gfhl non-null count ===')
print(conn.execute('SELECT COUNT(*), COUNT(txt), COUNT(orig) FROM gfhl').fetchone())
print()
print('=== hfhl (Hebrew Strong) sample ===')
rows = conn.execute('SELECT hsnum, txt, orig FROM hfhl LIMIT 3').fetchall()
for r in rows:
    print(f'hsnum={r[0]}, txt={str(r[1])[:80]}, orig={str(r[2])[:40]}')
print()
print('=== hfhl non-null count ===')
print(conn.execute('SELECT COUNT(*), COUNT(txt), COUNT(orig) FROM hfhl').fetchone())
print()
print('gfhl gsnum range:', conn.execute('SELECT MIN(gsnum), MAX(gsnum) FROM gfhl').fetchone())
print('hfhl hsnum range:', conn.execute('SELECT MIN(hsnum), MAX(hsnum) FROM hfhl').fetchone())
conn.close()
